const express = require('express');
const router = express.Router();
const controllerUser=require('../Controllers/controllerUser');
const verifyJWT = require('../middleware/verifyJWT');
const  checkSuperAdmin  = require('../middleware/cheksuperadmin');
const { UploadStream } = require('cloudinary');

router.post('/register',controllerUser.registerUser);
router.get('/getuserspending',controllerUser.getAllB2BUsers);
router.post('/updatestatu',verifyJWT,checkSuperAdmin,controllerUser.updateB2BStatus);
router.get('/getusebyname/:nameAgence',controllerUser.getB2BByNameAgence);
router.get('/getusersAccepted',controllerUser.getAllB2BUsersAccpe);
router.get('/getAgencyStats',controllerUser.getAgencyStats);
router.put('/modifcation/:nameAgence',verifyJWT,checkSuperAdmin,controllerUser.updateB2b);
router.delete('/delete/:nameAgence',verifyJWT,controllerUser.deleteB2b);
router.post('/agence/add', verifyJWT, controllerUser.addAgence);
router.post('/send-password-reset-email', controllerUser.sendResetPasswordEmail);
router.post('/reset-password/:email',controllerUser.resetPassword);
router.put("/update/:id",controllerUser.updateB2BInfo);
router.put("/update-password", controllerUser.updateB2BPassword);
router.get('/getagencebyid/:id',controllerUser.getB2BByidAgence);
module.exports = router;